baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Zhifei Yang'  # 你的名字

[params]
    author = "Zhifei Yang"
    description = "Undergraduate Student at Peking University"
    email = "zhifei.yeung@gmail.com"
    github = "https://github.com/isxiaohe"
    cv_url = "/cv.pdf"
    # scholar = "https://scholar.google.com/..."

[menu]
    [[menu.main]]
        name = "Publications"
        url = "/publications/"
        weight = 1
    [[menu.main]]
        name = "Notes"
        url = "/notes/"
        weight = 2