baseURL = 'https://isxiaohe.github.com/'
languageCode = 'en-us'
title = 'Zhifei Yang'
ignoreLogs = ['warning-goldmark-raw-html']

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true
                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [['$$', '$$']]
                    inline = [['$', '$']]
    [markup.highlight]
        style = 'github'
        lineNos = false
        codeFences = true

[params]
    author = "Zhifei Yang"
    description = "Undergraduate Student at Peking University"
    email = "zhifei.yeung@gmail.com"
    github = "https://github.com/isxiaohe"
    cv_url = "/cv.pdf"
    scholar = "https://scholar.google.com/citations?user=YOUR_ID"
